<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\kaldi-logo.png" />
    <None Remove="Assets\login-background.png" />
    <None Remove="Assets\splash-background.png" />
    <None Remove="Assets\Products\*.png" />
    <None Remove="Assets\Products\Kaldi\*.jpg" />
    <None Remove="Assets\Data\kaldi-menu.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controls\" />
    <Folder Include="Converters\" />
    <Folder Include="Data\" />
    <Folder Include="Models\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Utils\" />
    <Folder Include="Services\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\kaldi-logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\login-background.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\splash-background.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Products\*.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="Assets\Products\Kaldi\*.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Data\kaldi-menu.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
  </ItemGroup>

</Project>
